### PR TITLE
Updated use of the word include

### PR DESCRIPTION
**Pull request by MikeRayMSFT**
"include" is not a noun. Updated to refer to 
- include file
- include files
- include as a verb
- include extensions

### CODE REVIEW

**Comment by MonicaRush** [comment]
@MikeRayMSFT Mike -- I agree with your edit. We use a lot of shorthand internally that we shouldn't subject users to. Bill reviews PR's in the external guide. Bill, can you take a look? Thanks -- Monica

**Comment by MikeRayMSFT** [comment]
Thanks. I used extension because it's in the parent heading - https://github.com/MicrosoftDocs/Contribute/blob/6310e304536ba1ebbdf509c87da5324a63943dfe/Contribute/how-to-write-use-markdown.md#ops-custom-markdown-extensions

Having said that, I'm not 100% certain it's right. It actually looks like *file* could be used throughout.

**Comment by BillWagner** [comment]
Thanks for your patience @MikeRayMSFT 

I'll :shipit: now.

**Comment by JasonWHowell** [comment]
Thanks @MikeRayMSFT for paying it forward. I expect cookies next time!

**Pull request merged**
