### PR TITLE
Add metadata article

### PR DESCRIPTION
**Pull request by gewarren**
The public contributor guide doesn't have any info about metadata. This article adds it.

cc @ievangelist

### CODE REVIEW

**Comment by gewarren** [comment]
#sign-off

**Comment by Jim-Parker** [comment]
@sarah-barrett can you review and confirm that the information is appropriate for an external audience? Thanks
#hold-off

**Comment by sarah-barrett** [comment]
#sign-off I think this all looks fine.

**Comment by gewarren** [comment]
Thank you Jim and Sarah!

**Pull request merged**
