### PR TITLE
Compressed images in Contribute repo 

### PR DESCRIPTION
**Pull request by megan-nesbitt**
I used the compress image feature in Learn Authoring Pack/VS Code to automatically compress all images in repo.  It compressed 43 images. 

While making these updates, I noticed incorrect/outdated info in the **Image Compression article**.  I updated text in the article.  *****In addition**, I grabbed a brand-new screenshot for <configure-image-compression.png>.  It was old - had "Docs Image Extension" on existing screenshot.   

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [Contribute/docs-authoring/image-compression.md](https://github.com/MicrosoftDocs/Contribute/blob/9e22628ac5c6ff844c5107996646de12da507328/Contribute/docs-authoring/image-compression.md) | [Contribute/docs-authoring/image-compression](https://review.learn.microsoft.com/en-us/contribute/docs-authoring/image-compression?branch=pr-en-us-762) |

### CODE REVIEW

**Comment by megan-nesbitt** [comment]
#sign-off

**Comment by jehchow** [comment]
@megan-nesbitt Thanks for the effort here! In the **Files changed** tab, there are some images there that aren't displaying. When I look at the preview link, some images are showing properly, while others aren't (for example, `reformat-table.gif` is broken in: https://review.learn.microsoft.com/en-us/contribute/docs-authoring/reformat-table?branch=pr-en-us-762).

Can you go through the preview and determine which images aren't displaying and remove them from the PR? For the ones displaying on the **Files changed** tab, those should be ok, but you'll need to double-check the ones that say "Unable to render rich display".

**Comment by jehchow** [comment]
To address https://github.com/MicrosoftDocs/Contribute/issues/741.

**Comment by megan-nesbitt** [comment]
Closing this PR.  Created a new PR #763 to replace this PR.

**Pull request closed without merging**
