### PR TITLE
Update metadata.md

### PR DESCRIPTION
**Pull request by SeanMcCain-metadata**
Adding alert for upcoming retirement of ms.prot/ms.technology

# Contributor guide pull request

Thanks for contributing to the [Microsoft Learn contributor guide](https://learn.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.

## Quality control

- [ ] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [ ] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- If you have an open PR, tag the PR reviewers in comment with your question: `@carlyrevier, @jehchow`
- Open an issue in this repo and tag the PR reviewers.

### CODE REVIEW

**Comment by SeanMcCain-metadata** [comment]
#sign-off

**Comment by jehchow** [comment]
@SeanMcCain-metadata Since this is the external-facing contributor guide, the Platform manual link won't work. Please remove the link and replace with text that's appropriate to only non-Microsoft contributor audiences. Thanks! 

#hold-off while changes are made

**Comment by SeanMcCain-metadata** [comment]
Updated per Jeh's comment, link removed.

**Comment by SeanMcCain-metadata** [comment]
#sign-off

**Review by jehchow — APPROVED** [review]

**Comment by kasangi** [comment]
@carlyrevier how do we get this merged to live? Thanks! cc @SeanMcCain-metadata

**Comment by carlyrevier** [comment]
@kasangi - Yes, thank you for the reminder! Meant to do this last week and it slipped.

**Pull request merged**
