### PR TITLE
Ukrainian lang

### PR DESCRIPTION
**Pull request by andysvints**
Translation to Ukrainian language.

### CODE REVIEW

**Comment by Jim-Parker** [comment]
@JasonCard is Ukranian language on the list of translations for this guide?

**Comment by andysvints** [comment]
> 
> 
> @JasonCard is Ukranian language on the list of translations for this guide?

It is not. At this point Ukrainian version of this page do not exists.

**Comment by JasonCard** [comment]
Correct, Ukrainian (uk-UA) is currently not supported for this content.
Assigning to @nokura as localization owner of the external contributor guide to consider this request.

**Comment by Jim-Parker** [comment]
@JasonCard with the handoff to @nokura can we close this issue, or would it help to leave it open?

**Comment by JasonCard** [comment]
@Jim-Parker I'll go ahead and close for now, and @nokura can re-open if needed.

**Pull request closed without merging**
