### PR TITLE
[bulk] Updated relative links

### PR DESCRIPTION
**Pull request by MeeraDi**
# Contributor guide pull request

Thanks for contributing to the [docs.microsoft.com contributor guide](https://docs.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.

## Quality control

- [ ] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [ ] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- See our guidance on [Contributing to the contributor guide](/contribute/?branch=main) for help with adding or updating content in this contributor guide.
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`

### CODE REVIEW

**Comment by MeeraDi** [comment]
@v-andreaco, I've updated the links in this repo and they are ready for your review.

**Comment by v-andreaco** [comment]
@MeeraDi 

I'm a little confused. This PR looks like it might be a duplicate of https://github.com/MicrosoftDocs/Contribute/pull/592

Am I missing something?

**Comment by MeeraDi** [comment]
> @MeeraDi
> 
> I'm a little confused. This PR looks like it might be a duplicate of #592
> 
> Am I missing something?

@v-andreaco these are the additional relative link updates that you asked me to do because the repo might be renamed on 2/7. Since 592 was already merged and closed I created this new PR.

**Comment by v-andreaco** [comment]
Oh, I see!! I'm sorry, I should've clarified a little more. The rename is from 'master' to 'main', so the links I was talking about are on the **sensitiveLanguage** tab in our validation spreadsheet. There were some links that included the word 'master' and I meant that those links could be changed to 'main' in time for the rename on 2/7.

**Comment by MeeraDi** [comment]
Please close and disregard. Changes were addressed in other PRs.

**Pull request closed without merging**
