### PR TITLE
Added the FAQs of Git & GitHub

### PR DESCRIPTION
**Pull request by AbdulRehmanGHub**
# Contributor guide pull request

I have added simplified answers to frequently asked questions about Git and GitHub which will give users an easy to help materials to find their answers within no time.

## Quality control

- [x] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [x] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- If you have an open PR, tag the PR reviewers in comment with your question: `@carlyrevier, @jehchow`
- Open an issue in this repo and tag the PR reviewers.

### CODE REVIEW

**Comment by AbdulRehmanGHub** [comment]
#sign-off

**Comment by AbdulRehmanGHub** [comment]
@microsoft-github-policy-service agree

**Comment by carlyrevier** [comment]
Hi @AbdulRehmanGHub - Thanks for this addition. Did you write this content yourself? Or did it come from another FAQ somewhere?

**Comment by AbdulRehmanGHub** [comment]
> Hi @AbdulRehmanGHub - Thanks for this addition. Did you write this content yourself? Or did it come from another FAQ somewhere?

@carlyrevier I wrote these FAQs by myself with the latest and up to date answers.

**Review by carlyrevier — APPROVED** [review]
@AbdulRehmanGHub - This is a great addition. Thank you so much for the effort!

**Pull request merged**
