### PR TITLE
move .NET PR review process to the external guide.

### PR DESCRIPTION
**Pull request by BillWagner**
This was in the internal guide, but should be visible to our external contributors.

### CODE REVIEW

**Comment by MonicaRush** [comment]
Bill – Looks good. A few minor comments:

•	Fixed typo (“Publish high-quality content from out team” – changed “out” to “our”)
•	Just want to make sure external contributors will understand:
o	What a PR Merger webhook is. If not, might add something like “Many repositories don’t have PR Merger webhooks enabled, which automatically merge minor changes.”
o	What the CLA bot is (common legal agreement? – I don’t know)
•	I was not able to find the CONTRIBUTING.MD file. Did I miss something?

**Comment by MonicaRush** [comment]
@BillWagner Meant to @mention you. Happy New Year!

**Comment by BillWagner** [comment]
Thanks @MonicaRush 

I updated the article based on your feedback above.

**Comment by MonicaRush** [comment]
@BillWagner Perfect. Thank you. Just hate to trip people up with our obscure language. #sign-off

**Comment by BillWagner** [comment]
@MonicaRush Can you add an approved review? Then I'll merge it.

**Pull request merged**
