### PR TITLE
Learn rebrand updates

### PR DESCRIPTION
**Pull request by jennsteiner74**
# Contributor guide pull request

Thanks for contributing to the [docs.microsoft.com contributor guide](https://docs.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.

## Quality control

- [ ] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [ ] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- See our guidance on [Contributing to the contributor guide](/contribute/?branch=main) for help with adding or updating content in this contributor guide.
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`

### CODE REVIEW

**Comment by jennsteiner74** [comment]
#sign-off

**Review by jehchow — APPROVED** [review]

**Comment by jennsteiner74** [comment]
#sign-off

**Review by jehchow — APPROVED** [review]

**Comment by Lemmingh** [comment]
Out of curiosity, is there any announcement about this rebranding? Seems nothing so far:

* <https://www.bing.com/search?q=Microsoft+Docs+rebrand>

* <https://www.bing.com/search?q=Microsoft+Docs+is+now+Microsoft+Learn>

* <https://twitter.com/docsmsft>

* <https://docs.microsoft.com/en-us/teamblog/>

* <https://techcommunity.microsoft.com/t5/microsoft-learn/ct-p/MicrosoftLearn>

---

I'm quite confused, since Microsoft Learn used to be a section of Microsoft Docs (`docs.microsoft.com`) but now becomes its name, just like children swap identities with their parents.

**Comment by jehchow** [comment]
> Out of curiosity, is there any announcement about this rebranding? Seems nothing so far:
> 
> * https://www.bing.com/search?q=Microsoft+Docs+rebrand
> * https://www.bing.com/search?q=Microsoft+Docs+is+now+Microsoft+Learn
> * https://twitter.com/docsmsft
> * https://docs.microsoft.com/en-us/teamblog/
> * https://techcommunity.microsoft.com/t5/microsoft-learn/ct-p/MicrosoftLearn
> 
> I'm quite confused, since Microsoft Learn used to be a section of Microsoft Docs (`docs.microsoft.com`) but now becomes its name, just like children swap identities with their parents.

Hi @Lemmingh! Here is the blog post with the announcement: https://techcommunity.microsoft.com/t5/microsoft-learn-blog/build-skills-that-open-doors-with-microsoft-learn/ba-p/3614011

There is currently an announcement link to this post at the top of the page across many of the pages on our site. Hope the information in the blog helps!

**Pull request merged**
