### PR TITLE
Update priority descriptions

### PR DESCRIPTION
**Pull request by tdykstra**
[Internal review URL](https://review.docs.microsoft.com/en-us/contribute/dotnet/labels-projects?branch=pr-en-us-447#priority)

@gewarren @BillWagner please review

### CODE REVIEW

**Review by gewarren — APPROVED** [review]
At some point we'll have to change these to PriX instead of PX, correct?

**Comment by tdykstra** [comment]
Probably 😄

**Comment by Jim-Parker** [comment]
@tdykstra is this okay to merge?

**Comment by tdykstra** [comment]
#sign-off

**Pull request merged**
