### PR TITLE
Add supported identifier

### PR DESCRIPTION
**Pull request by Youssef1313**
Same like with https://github.com/dotnet/docs/pull/15471

### CODE REVIEW

**Comment by tdykstra** [comment]
#sign-off

**Comment by Jim-Parker** [comment]
@tdykstra @Youssef1313 There is a merge conflict suggestion noted in the build validation report. Can you take a look and fix?

**Comment by Youssef1313** [comment]
@Jim-Parker, Can you confirm if it's fixed now ?

**Comment by tdykstra** [comment]
@Youssef1313 The build still shows conflicts in 
Contribute/validation-reference/multiple-h1s.md
and 
Contribute/validation-reference/h1-in-moniker.md

**Comment by Youssef1313** [comment]
@tdykstra, Strange for me, I didn't even edit these files. And GitHub UI doesn't show that there is conflicts. However, I updated them to be the same as the current master. Can you re-check please ?

**Comment by Jim-Parker** [comment]
@Youssef1313 @tdykstra The suggestions are still showing in the build report. I've asked @meganbradley to help clarify since this is related to several PRs. Thanks.

**Pull request merged**
