### PR TITLE
Add support for snippet reference from a Jupyter notebook cell

### PR DESCRIPTION
**Pull request by sdgilley**

### CODE REVIEW

**Comment by sdgilley** [comment]
@tdykstra - can you review please?

**Review by tdykstra — APPROVED** [review]

**Comment by sdgilley** [comment]
#sign-off

**Comment by sdgilley** [comment]
@tdykstra ?  This still says review required?

**Comment by tdykstra** [comment]
>This still says review required?

That never goes away, because GitHub only counts reviews by people with write access to the repo. @Jim-Parker can see that it's been reviewed and will merge when he sees the sign-off comment.

**Review by Jim-Parker — APPROVED** [review]

**Pull request merged**
