### PR TITLE
Adjusted spacing of ordered list example

### PR DESCRIPTION
**Pull request by sdwheeler**
Adjusted spacing of ordered list example for CommonMark compliance.

### CODE REVIEW

**Comment by JasonWHowell** [comment]
@sdwheeler @BillWagner Watch which branch changes goes into. Live vs. Master. We have changes in both, so that's confusing. I think we should use master whenever possible.

**Comment by sdwheeler** [comment]
@BillWagner @JasonWHowell Weird, I don't know how or why live was selected as the target. That was not my intent.

**Comment by JasonWHowell** [comment]
@sdwheeler Yeah. It is easy to happen. Discussing with Bill how to default to master. He knows where to switch it.

**Comment by BillWagner** [comment]
This was an older PR. I had fixed this in #51 so we should be set now.

**Pull request merged**
