### PR TITLE
Update note-docsitelocfeedback.md

### PR DESCRIPTION
**Pull request by SunnyDeng**
# Contributor guide pull request

Thanks for contributing to the [Microsoft Learn documentation contributor guide](https://learn.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.

## Quality control

- [ ] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [ ] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- See our guidance on [Contributing to the contributor guide](/contribute/?branch=main) for help with adding or updating content in this contributor guide.
- Write to the PR reviewer in the PR comments: `@carlyrevier, @jehchow`

### CODE REVIEW

**Comment by SunnyDeng** [comment]
@Jim-Parker @jehchow please review as we changed the loc feedback channel.
#sign-off

**Review by jehchow — APPROVED** [review]

**Comment by jehchow** [comment]
@SunnyDeng LGTM - Please comment `#sign-off` if you're ready for this to be merged. Thank you!

**Comment by SunnyDeng** [comment]
@jehchow interesting ... i did back to 4 days ago. Now #sign-off again, please check.

**Comment by jehchow** [comment]
> @jehchow interesting ... i did back to 4 days ago. Now #sign-off again, please check.

@SunnyDeng  Oops, I missed that in your prior comment! My fault :)

**Pull request merged**
