### PR TITLE
External guide - updating all metadata and titles

### PR DESCRIPTION
**Pull request by JasonWHowell**

### CODE REVIEW

**Comment by JasonWHowell** [comment]
@MonicaRush 
This PR updates the metadata on the external guide for reporting consistency. 
I adjusted Title and descriptions and H1 to try to always mention docs.microsoft.com for SEO consistency.
Happy for another set of eyes to look before we publish.
#sign-off

**Comment by JasonWHowell** [comment]
@Jim-Parker could you please review this PR for the external guide. Its just metadata changes. I think we could do better on Titles and H1s for consistency (mention docs / docs.microsoft.com / etc).

**Comment by Jim-Parker** [comment]
@JasonWHowell I added my review. Is anything else needed to make this mergeable?

**Comment by JasonWHowell** [comment]
@Jim-Parker I think its fine. I see a merge button, and tempting to push it, but I'll wait for @MonicaRush

**Pull request merged**
